name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    name: "Î» ${{ matrix.ghc }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.7.1"]
        ghc: ["9.0.1"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: haskell/actions/setup@v1
      name: ğŸ—ï¸ Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: ${{ matrix.stack }}

    - name: ğŸ—ï¸ Install Z3
      uses: pavpanchekha/setup-z3@1.2.2

    - uses: actions/cache@v2.1.3
      name: ğŸ¦ Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: ğŸ—ï¸ Install dependencies
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: ğŸš§ Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: ğŸš¨ Test
      run: |
        stack test --system-ghc
